server {
  listen 80;
  server_name booksharecommunity.org; 

  # Redirect HTTP to HTTPS
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name booksharecommunity.org;

  ssl_certificate /etc/letsencrypt/live/booksharecommunity.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/booksharecommunity.org/privkey.pem;

  root /app/public;
  index index.html;

  # Static assets served directly
  location ~ ^/(assets|packs|static|favicon.ico|robots.txt) {
    try_files $uri @proxy;
    expires max;
    add_header Cache-Control public;
  }

  location / {
    try_files $uri @proxy;
  }

  location @proxy {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://web:3000;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }

  # healthcheck
  location /healthz {
    return 200 "ok\n";
  }
}
