
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: givingshelf_dev
  username: gs_user
  password:

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "givingshelf_test") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "gs_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

bookshare:
  <<: *default
  database: <%= ENV.fetch("BOOKSHARE_DB_NAME", "bookshare_dev") %>
  username: <%= ENV.fetch("BOOKSHARE_DB_USERNAME", "bs_user") %>
  password: <%= ENV.fetch("BOOKSHARE_DB_PASSWORD", "") %>

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    sslmode: require
  cache:
    <<: *default
    <% if ENV["DATABASE_URL"] %>
    <% db_uri = URI.parse(ENV["DATABASE_URL"]) %>
    host: <%= db_uri.host || "db" %>
    port: <%= db_uri.port || 5432 %>
    username: <%= db_uri.user %>
    password: <%= db_uri.password %>
    <% else %>
    host: <%= ENV.fetch("DATABASE_HOST", "db") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    username: <%= ENV.fetch("DATABASE_USERNAME", ENV["POSTGRES_USER"]) %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", ENV["POSTGRES_PASSWORD"]) %>
    <% end %>
    database: givingshelf_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    <% if ENV["DATABASE_URL"] %>
    <% db_uri = URI.parse(ENV["DATABASE_URL"]) %>
    host: <%= db_uri.host || "db" %>
    port: <%= db_uri.port || 5432 %>
    username: <%= db_uri.user %>
    password: <%= db_uri.password %>
    <% else %>
    host: <%= ENV.fetch("DATABASE_HOST", "db") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    username: <%= ENV.fetch("DATABASE_USERNAME", ENV["POSTGRES_USER"]) %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", ENV["POSTGRES_PASSWORD"]) %>
    <% end %>
    database: givingshelf_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    <% if ENV["DATABASE_URL"] %>
    <% db_uri = URI.parse(ENV["DATABASE_URL"]) %>
    host: <%= db_uri.host || "db" %>
    port: <%= db_uri.port || 5432 %>
    username: <%= db_uri.user %>
    password: <%= db_uri.password %>
    <% else %>
    host: <%= ENV.fetch("DATABASE_HOST", "db") %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    username: <%= ENV.fetch("DATABASE_USERNAME", ENV["POSTGRES_USER"]) %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", ENV["POSTGRES_PASSWORD"]) %>
    <% end %>
    database: givingshelf_production_cable
    migrations_paths: db/cable_migrate
